config/routes.rb
Rails.application.routes.draw do
  get 'comments/new'
  get 'comments/create'
  root 'welcome#index'
  resources :posts do
      resources :comments
  end
  resources :pages
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get '/posts/:post_id/comments/:id/form', to:'comments#form', as: 'form'
  get '/form.js', to: 'comments#form', as: 'form'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/page.rb
class Page < ApplicationRecord
    after_create :update_slug
    before_update :assign_slug
    validates :slug, uniqueness: true
    validates :title, presence: true
    
    def generate_slug
        title.squish.downcase.gsub('.', '').gsub(' ', '-')
    end
    
    def update_slug
        update_attribute(:slug, generate_slug)
    end
    
    def to_param
        self.slug
    end

    private 
    
    def assign_slug
        self.slug = generate_slug
    end
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :set_post, only: [:create, :edit, :update, :destroy]
  def create
        @comment = @post.comments.create(comment_params)
    
    if @comment.save
      redirect_to @post, anchor: :back
    else 
      render plain: "ya done messed up bruthuh"
    end
  end

  def edit 
    @comment = Comment.find(params[:id])
    
    render partial: 'form', locals: { comment: @comment } 
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to @post
    else
      render plain: "Ya done messed up boy!"
    end
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to @post
  end



  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:name, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    before_action :set_page, only: %i[ show edit update destroy ]

    def index
        @pages = Page.all    
    end

    def show
        @comment = Post.first.comments.first
        @comments = Post.first.comments
    end

    def new
        @page = Page.new
    end

    def create
        @page = Page.new(page_params)

        if @page.save 
            redirect_to @page
        else
            render plain: 'ya done messed up son!'
        end
    end

    def edit
    end

    def update
        if @page.update(page_params)
            redirect_to @page
        else
            render plain: 'you keep messen uppa!'
        end
    end

    def destroy
        @page.destroy
        redirect_to pages_url
        
    end


    private
    
    def set_page 
        @page = Page.find_by_slug(params[:id])
        if @page.nil?
            flash[:notice] = "We couldn't find that Post."
            redirect_to pages_url
        end
    end

    def page_params 
        params.require(:page).permit(:title, :body)
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comments = @post.comments.paginate(page: params[:page], per_page: 5)
    @comment = @post.comments.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<div style="border:1px solid black; margin:1.5rem; padding: 1.5rem; border-radius: 5px; background-color: #000011; color: #EEEEFF; max-width: 200px; display: inline-block">
<h5><%= comment.name %> said</h5>
<p><%= comment.body %></p>
<em><small><%= comment.updated_at.strftime('%B %d, %Y') %></small></em>
<div class='comment-admin'>
    <a class="edit-link">Edit</a>
    <div id="edit-comment-form" class="hide">
        <h5>Edit Comment</h5>
    <%= render partial: 'comments/form', locals: { post: @post, comment: comment } %>
</div>
</div>
<%= link_to 'Delete', [@post, comment], method: :delete %>
</div>

app/views/comments/_form.html.erb
<h1>Create a new comment!</h1>
    <%= form_with model: [@post, comment] do |form| %>
        <%= form.label :name, "Name" %>
        <%= form.text_field :name %>
        <%= form.label :body, "Body" %>
        <%= form.text_field :body %>
        <%= form.submit 'Do it!' %>

    <% end %>

    <%= link_to "Back", @post %>

app/views/comments/new.html.erb
<h1>Create a new comment!</h1>
    <%= form_with model: @comment do |form| %>
        <%= form.label :name, "Name" %>
        <%= form.text_field :name %>
        <%= form.label :body, "Body" %>
        <%= form.text_field :body %>
        <%= form.submit 'Do it!' %>

    <% end %>

    <%= link_to "Back", @post %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PgApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/edit.html.erb
<h1>Update page!</h1>

    <%= form_with(model: @page) do |form| %>
        <%= form.label :title, "Title" %>
        <%= form.text_field :title %>
        <%= form.label :body, "Body" %>
        <%= form.text_field :body %>
        <%= form.submit 'Do it!' %>

    <% end %>

    <%= link_to "Back", @page %>

app/views/pages/index.html.erb
<h1>Blog Pages</h1>
<p id="notice"><%= notice %></p>
<% @pages.each do |p| %>
    <h2> <%= link_to p.title, p %> </h2>
        <table>
            <tr>
                <th>Content</th>
                <th>Slug</th>
            </tr>
            <tr>
                <td><%=p.body%></td>
                <td><%=p.slug%></td>
            </tr>
        </table>
<% end %>

<%= link_to 'Back', root_path %>
<%= link_to "Create New Page", new_page_path %>
    <% if @pages.empty? %>
        <%= "not found!" %>
    <% end %>

app/views/pages/new.html.erb
<h1>Create a new page!</h1>
    <%= form_with model: @page do |form| %>
        <%= form.label :title, "Title" %>
        <%= form.text_field :title %>
        <%= form.label :body, "Body" %>
        <%= form.text_field :body %>
        <%= form.submit 'Do it!' %>

    <% end %>

    <%= link_to "Back", pages_path %>

app/views/pages/show.html.erb
<h1><%= @page.title %></h1>
<p><%= @page.body %></p>
<h1><%= @comment.body %></h1>
<ul>
    <% @comments.each do |c| %>
        <li> <%= c.body %> </li>
    <% end %>
</ul>
<h1 style="color:teal"> <%= @comment.post.title %>, <%= @comment.post.body %></h1>
    
<%= link_to "Edit", edit_page_path(@page) %> | 
<%= link_to "Back", pages_path %> | 
<%= link_to "Delete", @page, method: :delete, data: {confirm: "You sure about dat!?"} %>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, style: "resize: none; width: 500px" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', root_path %>
<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>
<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<%= will_paginate @comments %>

<div style="display:flex;flex-direction:row;align-items:flex-start">

<%= render partial: 'comments/comment', collection: @comments %>

</div>

<%= will_paginate @comments %>

<div id="edit-comment-form" class="hide">
<h3>Edit Comment</h3>
    <%= render partial: 'form', locals: { post: @post } %>
</div>

<h3>Add a Comment</h3>

<%# render partial: 'comments/form', locals: { comment: @post.comments.new } %>

<%= render 'comments/form', comment: @comment %>

<%= link_to 'Edit', edit_post_path(@post) %> |

<%= link_to 'Back', posts_path %>

<%= javascript_pack_tag 'comment-form' %>

app/views/welcome/index.html.erb
<h2>Hello World</h2>
<p>
  The time is now: <%= Time.now %>
</p>

<%= link_to "Posts", posts_path %>
<%= link_to "Pages", pages_path %>